const boards = {
  "simple": {
    "name": "board0",
    "rows": 3,
    "columns": 6,
    "tiles": [{
      "type": "textAndIcon",
      "displayName": "want",
      "iconName": "want",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "more",
      "iconName": "more",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "not",
      "iconName": "not",
      "colour": "grey"
    }, {
      "type": "textAndIcon",
      "displayName": "go",
      "iconName": "go",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "help",
      "iconName": "help",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "look",
      "iconName": "look",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "play",
      "iconName": "play",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "same",
      "iconName": "same",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "different",
      "iconName": "different",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "what",
      "iconName": "what",
      "colour": "pink"
    }, {
      "type": "textAndIcon",
      "displayName": "like",
      "iconName": "like",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "stop",
      "iconName": "stop",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "drink",
      "iconName": "drink",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "eat",
      "iconName": "eat",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "turn",
      "iconName": "turn",
      "colour": "grey"
    }, {
      "type": "textAndIcon",
      "displayName": "up",
      "iconName": "up",
      "colour": "red"
    }, {
      "type": "textAndIcon",
      "displayName": "down",
      "iconName": "down",
      "colour": "red"
    }, {
      "type": "textAndIcon",
      "displayName": "finish",
      "iconName": "finish",
      "colour": "green"
    }]
  },

  "main": {
    "name": "board1",
    "rows": 6,
    "columns": 9,
    "tiles": [{
      "type": "link",
      "displayName": "Toys",
      "iconName": "toys",
      "linkTo": "toys",
      "colour": "linkColour"
    }, {
      "type": "link",
      "displayName": "Learn",
      "iconName": "learn",
      "linkTo": "learn",
      "colour": "linkColour"
    }, {
      "type": "link",
      "displayName": "Topic",
      "iconName": "topic",
      "linkTo": "topic",
      "colour": "linkColour"
    }, {
      "type": "link",
      "displayName": "Body",
      "iconName": "body",
      "linkTo": "body",
      "colour": "linkColour"
    }, {
      "type": "link",
      "displayName": "Home",
      "iconName": "home",
      "linkTo": "home",
      "colour": "linkColour"
    }, {
      "type": "link",
      "displayName": "Food",
      "iconName": "food",
      "linkTo": "food",
      "colour": "linkColour"
    }, {
      "type": "link",
      "displayName": "Drinks",
      "iconName": "drinks",
      "linkTo": "drinks",
      "colour": "linkColour"
    }, {
      "type": "link",
      "displayName": "People",
      "iconName": "people",
      "linkTo": "people",
      "colour": "linkColour"
    }, {
      "type": "link",
      "displayName": "Feelings",
      "iconName": "feelings",
      "linkTo": "feelings",
      "colour": "linkColour"
    }, {
      "type": "textAndIcon",
      "displayName": "I",
      "iconName": "i",
      "colour": "yellow",
      "pronounciation":"eye"
    }, {
      "type": "textAndIcon",
      "displayName": "want",
      "iconName": "want",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "more",
      "iconName": "more",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "not",
      "iconName": "not",
      "colour": "grey"
    }, {
      "type": "textAndIcon",
      "displayName": "go",
      "iconName": "go",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "help",
      "iconName": "help",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "look",
      "iconName": "look",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "need",
      "iconName": "need",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "have",
      "iconName": "have",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "you",
      "iconName": "you",
      "colour": "yellow"
    }, {
      "type": "textAndIcon",
      "displayName": "play",
      "iconName": "play",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "same",
      "iconName": "same",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "different",
      "iconName": "different",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "what",
      "iconName": "what",
      "colour": "pink"
    }, {
      "type": "textAndIcon",
      "displayName": "like",
      "iconName": "like",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "stop",
      "iconName": "stop",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "where",
      "iconName": "where",
      "colour": "pink"
    }, {
      "type": "textAndIcon",
      "displayName": "in",
      "iconName": "in",
      "colour": "red"
    }, {
      "type": "textAndIcon",
      "displayName": "he",
      "iconName": "he",
      "colour": "yellow"
    }, {
      "type": "textAndIcon",
      "displayName": "eat",
      "iconName": "eat",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "drink",
      "iconName": "drink",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "turn",
      "iconName": "turn",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "up",
      "iconName": "up",
      "colour": "red"
    }, {
      "type": "textAndIcon",
      "displayName": "down",
      "iconName": "down",
      "colour": "red"
    }, {
      "type": "textAndIcon",
      "displayName": "finish",
      "iconName": "finish",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "who",
      "iconName": "who",
      "colour": "pink"
    }, {
      "type": "textAndIcon",
      "displayName": "on",
      "iconName": "on",
      "colour": "red"
    }, {
      "type": "textAndIcon",
      "displayName": "she",
      "iconName": "she",
      "colour": "yellow"
    }, {
      "type": "textAndIcon",
      "displayName": "do",
      "iconName": "do",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "loud",
      "iconName": "loud",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "quiet",
      "iconName": "quiet",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "fast",
      "iconName": "fast",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "slow",
      "iconName": "slow",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "funny",
      "iconName": "funny",
      "colour": "blue"
    }, {
      "type": "textAndIcon",
      "displayName": "talk",
      "iconName": "talk",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "off",
      "iconName": "off",
      "colour": "red"
    }, {
      "type": "textAndIcon",
      "displayName": "it",
      "iconName": "it",
      "colour": "yellow"
    }, {
      "type": "textAndIcon",
      "displayName": "put",
      "iconName": "put",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "make",
      "iconName": "make",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "feel",
      "iconName": "feel",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "think",
      "iconName": "think",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "is",
      "iconName": "is",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "close",
      "iconName": "close",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "open",
      "iconName": "open",
      "colour": "green"
    }, {
      "type": "textAndIcon",
      "displayName": "here",
      "iconName": "here",
      "colour": "grey"
    }]
  },

  "toys": {
    "name": "board2",
    "rows": 6,
    "columns": 9,
    "tiles": [{
      "type": "link",
      "displayName": "Back",
      "iconName": "navigate-back",
      "linkTo": "main",
      "colour": "linkColour"
    }, {
      "type": "textAndIcon",
      "displayName": "toy",
      "iconName": "toys",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "game",
      "iconName": "game",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "computer",
      "iconName": "computer",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "tablet",
      "iconName": "tablet",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "phone",
      "iconName": "phone",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "ball",
      "iconName": "ball",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bubbles",
      "iconName": "bubbles",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "balloon",
      "iconName": "balloon",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "blocks",
      "iconName": "blocks",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "foam",
      "iconName": "foam",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "spinner",
      "iconName": "spinner",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "yo-yo",
      "iconName": "yo-yo",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "stretchy bands",
      "iconName": "stretchy-band",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "wind up",
      "iconName": "wind-up",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "jigsaw",
      "iconName": "jigsaw",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "mr potato",
      "iconName": "mr-potato",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "dice",
      "iconName": "dice",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "doll",
      "iconName": "doll",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "teddy",
      "iconName": "teddy",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "board game",
      "iconName": "board-game",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "book",
      "iconName": "book",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "sing",
      "iconName": "sing",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "music",
      "iconName": "music",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "dance",
      "iconName": "dance",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "clap",
      "iconName": "clap",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "tickle",
      "iconName": "tickle",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "push",
      "iconName": "push",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "climb",
      "iconName": "climb",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "read",
      "iconName": "read",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "sand pit",
      "iconName": "sand-pit",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "water tray",
      "iconName": "water-tray",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "swing",
      "iconName": "swing",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "slide",
      "iconName": "slide",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "roundabout",
      "iconName": "roundabout",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "seesaw",
      "iconName": "seesaw",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "ladder",
      "iconName": "ladder",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "bike",
      "iconName": "bike",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "scooter",
      "iconName": "scooter",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }]
  },

  "learn": {
    "name": "board3",
    "rows": 6,
    "columns": 9,
    "tiles": [{
      "type": "link",
      "displayName": "Back",
      "iconName": "navigate-back",
      "linkTo": "main",
      "colour": "linkColour"
    }, {
      "type": "textOnly",
      "displayName": "⠀0⠀",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "add",
      "iconName": "add",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "minus",
      "iconName": "minus",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "divide",
      "iconName": "divide",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "times",
      "iconName": "times",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "equals",
      "iconName": "equals",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "count",
      "iconName": "count",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "⠀1⠀",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "⠀2⠀",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "⠀3⠀",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "⠀4⠀",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "⠀5⠀",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "⠀6⠀",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "⠀7⠀",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "⠀8⠀",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "⠀9⠀",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "learn",
      "iconName": "learn",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "cut",
      "iconName": "cut",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "colour",
      "iconName": "colour-activity",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "paint",
      "iconName": "paint",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "red",
      "iconName": "red",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "orange",
      "iconName": "orange-colour",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "yellow",
      "iconName": "yellow",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "green",
      "iconName": "green",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "blue",
      "iconName": "blue",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "purple",
      "iconName": "purple",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pink",
      "iconName": "pink",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "black",
      "iconName": "black",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "brown",
      "iconName": "brown",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "stripes",
      "iconName": "stripes",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "dots",
      "iconName": "dots",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "grey",
      "iconName": "grey",
      "colour": "red",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pen",
      "iconName": "pen",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pencil",
      "iconName": "pencil",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "scissors",
      "iconName": "scissors",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sharpener",
      "iconName": "sharpener",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "ruler",
      "iconName": "ruler",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "glitter",
      "iconName": "glitter",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "light",
      "iconName": "light",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "heavy",
      "iconName": "heavy",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "dark",
      "iconName": "dark",
      "colour": "grey",
      "linkTo": "main"
    }]
  },

  "topic": {
    "name": "board4",
    "rows": 6,
    "columns": 9,
    "tiles": [{
      "type": "link",
      "displayName": "Back",
      "iconName": "navigate-back",
      "linkTo": "main",
      "colour": "linkColour"
    }, {
      "type": "textAndIcon",
      "displayName": "animal",
      "iconName": "animal",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pet",
      "iconName": "pet",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "zoo",
      "iconName": "zoo",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "farm",
      "iconName": "farm",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "wild",
      "iconName": "wild",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "fluffy",
      "iconName": "fluffy",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "big",
      "iconName": "big",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "cat",
      "iconName": "cat",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "dog",
      "iconName": "dog",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "rabbit",
      "iconName": "rabbit",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "hamster",
      "iconName": "hamster",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "lizard",
      "iconName": "lizard",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "tortoise",
      "iconName": "tortoise",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "snake",
      "iconName": "snake",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bird",
      "iconName": "bird",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "cow",
      "iconName": "cow",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sheep",
      "iconName": "sheep",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "chicken",
      "iconName": "chicken",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "horse",
      "iconName": "horse",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pig",
      "iconName": "pig",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "elephant",
      "iconName": "elephant",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "spider",
      "iconName": "spider",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bug",
      "iconName": "bug",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "small",
      "iconName": "small",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "car",
      "iconName": "car",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bus",
      "iconName": "bus",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "train",
      "iconName": "train",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "motorbike",
      "iconName": "motorbike",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "plane",
      "iconName": "plane",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "helicopter",
      "iconName": "helicopter",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "boat",
      "iconName": "boat",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "paw",
      "iconName": "paw",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "tail",
      "iconName": "tail",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "claw",
      "iconName": "claw",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "wheel",
      "iconName": "wheel",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "left",
      "iconName": "left",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "right",
      "iconName": "right",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "drive",
      "iconName": "drive",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "fly",
      "iconName": "fly",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "ride",
      "iconName": "ride",
      "colour": "green",
      "linkTo": "main"
    }]
  },

  "body": {
    "name": "board5",
    "rows": 6,
    "columns": 9,
    "tiles": [{
      "type": "link",
      "displayName": "Back",
      "iconName": "navigate-back",
      "linkTo": "main",
      "colour": "linkColour"
    }, {
      "type": "textAndIcon",
      "displayName": "body",
      "iconName": "body",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "poo",
      "iconName": "poo",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "wee",
      "iconName": "wee",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "hurt",
      "iconName": "hurt",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "blood",
      "iconName": "blood",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "itch",
      "iconName": "itch",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "broken",
      "iconName": "broken",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bruise",
      "iconName": "bruise",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "nappy",
      "iconName": "nappy",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "finger",
      "iconName": "finger",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "hand",
      "iconName": "hand",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "arm",
      "iconName": "arm",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "elbow",
      "iconName": "elbow",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "tummy",
      "iconName": "tummy",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "private parts",
      "iconName": "private-parts",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "eye",
      "iconName": "eye",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "nose",
      "iconName": "nose",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "mouth",
      "iconName": "mouth",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "toe",
      "iconName": "toe",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "foot",
      "iconName": "foot",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "leg",
      "iconName": "leg",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "knee",
      "iconName": "knee",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "chest",
      "iconName": "chest",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "head",
      "iconName": "head",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "ear",
      "iconName": "ear",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "hair",
      "iconName": "hair",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "tooth",
      "iconName": "tooth",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pants",
      "iconName": "pants",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "socks",
      "iconName": "socks",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "shoe",
      "iconName": "shoe",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "trousers",
      "iconName": "trousers",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "shorts",
      "iconName": "shorts",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "shirt",
      "iconName": "shirt",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "skirt",
      "iconName": "skirt",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "tights",
      "iconName": "tights",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "jumper",
      "iconName": "jumper",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "zip",
      "iconName": "zip",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "button",
      "iconName": "button",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "lace",
      "iconName": "lace",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "velcro",
      "iconName": "velcro",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "coat",
      "iconName": "coat",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }]
  },

  "home": {
    "name": "board5",
    "rows": 6,
    "columns": 9,
    "tiles": [{
      "type": "link",
      "displayName": "Back",
      "iconName": "navigate-back",
      "linkTo": "main",
      "colour": "linkColour"
    }, {
      "type": "textAndIcon",
      "displayName": "school",
      "iconName": "school",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "home",
      "iconName": "home",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "park",
      "iconName": "park",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "swimming pool",
      "iconName": "swimming-pool",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "restaurant",
      "iconName": "restaurant",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "shop",
      "iconName": "shop",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "outside",
      "iconName": "outside",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "weather",
      "iconName": "weather",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "toilet",
      "iconName": "toilet",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "kitchen",
      "iconName": "kitchen",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "living room",
      "iconName": "living-room",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bedroom",
      "iconName": "bedroom",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bathroom",
      "iconName": "bathroom",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "dining room",
      "iconName": "dining-room",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "stairs",
      "iconName": "stairs",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "garden",
      "iconName": "garden",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "rain",
      "iconName": "rain",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "cooker",
      "iconName": "cooker",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "soap",
      "iconName": "soap",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "chair",
      "iconName": "chair",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bed",
      "iconName": "bed",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "swim",
      "iconName": "swim",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "table",
      "iconName": "table",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "buy",
      "iconName": "buy",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "window",
      "iconName": "window",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sun",
      "iconName": "sun",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "cook",
      "iconName": "cook",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sponge",
      "iconName": "sponge",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sofa",
      "iconName": "sofa",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sleep",
      "iconName": "sleep",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bath",
      "iconName": "bath",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "cutlery",
      "iconName": "cutlery",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "money",
      "iconName": "money",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "door",
      "iconName": "door",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "cloud",
      "iconName": "cloud",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "towel",
      "iconName": "towel",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "TV",
      "iconName": "tv",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "sink",
      "iconName": "sink",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "dish",
      "iconName": "dish",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "mud",
      "iconName": "mud",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "wash",
      "iconName": "wash",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sit",
      "iconName": "sit",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "shower",
      "iconName": "shower",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "hot",
      "iconName": "hot",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "cold",
      "iconName": "cold",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "snow",
      "iconName": "snow",
      "colour": "grey",
      "linkTo": "main"
    }]
  },

  "food": {
    "name": "board6",
    "rows": 6,
    "columns": 9,
    "tiles": [{
      "type": "link",
      "displayName": "Back",
      "iconName": "navigate-back",
      "linkTo": "main",
      "colour": "linkColour"
    }, {
      "type": "textAndIcon",
      "displayName": "food",
      "iconName": "food",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "sauce",
      "iconName": "sauce",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "breakfast",
      "iconName": "breakfast",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "lunch",
      "iconName": "lunch",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "tea",
      "iconName": "tea",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "snack",
      "iconName": "snack",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "meal",
      "iconName": "meal",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "mash",
      "iconName": "mash",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "curry",
      "iconName": "curry",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "rice",
      "iconName": "rice",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pasta",
      "iconName": "pasta",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pizza",
      "iconName": "pizza",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "favourite",
      "iconName": "favourite",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "burned",
      "iconName": "burned",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "healthy",
      "iconName": "healthy",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "veg",
      "iconName": "veg",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "carrot",
      "iconName": "carrot",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "broccoli",
      "iconName": "broccoli",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "potato",
      "iconName": "potato",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pea",
      "iconName": "pea",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bean",
      "iconName": "bean",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "tomato",
      "iconName": "tomato",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "salad",
      "iconName": "salad",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "bread",
      "iconName": "bread",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "meat",
      "iconName": "meat",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "fish",
      "iconName": "fish",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "ham",
      "iconName": "ham",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "chicken",
      "iconName": "chicken",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "tuna",
      "iconName": "tuna",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "nugget",
      "iconName": "nugget",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "burger",
      "iconName": "burger",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sausage",
      "iconName": "sausage",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "toast",
      "iconName": "toast",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "cereal",
      "iconName": "cereal",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "egg",
      "iconName": "egg",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "cheese",
      "iconName": "cheese",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "chocolate",
      "iconName": "chocolate",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "biscuit",
      "iconName": "biscuit",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "crisp",
      "iconName": "crisp",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "chip",
      "iconName": "chip",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sandwich",
      "iconName": "sandwich",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "soup",
      "iconName": "soup",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "noodles",
      "iconName": "noodles",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pancake",
      "iconName": "pancake",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "yogurt",
      "iconName": "yogurt",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "butter",
      "iconName": "butter",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "jam",
      "iconName": "jam",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sweet",
      "iconName": "sweet",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "spicy",
      "iconName": "spicy",
      "colour": "pink",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "wrap",
      "iconName": "wrap",
      "colour": "grey",
      "linkTo": "main"
    }]
  },

  "drinks": {
    "name": "board7",
    "rows": 6,
    "columns": 9,
    "tiles": [{
      "type": "link",
      "displayName": "Back",
      "iconName": "navigate-back",
      "linkTo": "main",
      "colour": "linkColour"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "hot",
      "iconName": "hot",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "cold",
      "iconName": "cold",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "juice",
      "iconName": "juice",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "water",
      "iconName": "water",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "milk",
      "iconName": "milk",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "milkshake",
      "iconName": "milkshake",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "fizzy",
      "iconName": "fizzy",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "lemonade",
      "iconName": "lemonade",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "cola",
      "iconName": "cola",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "tea",
      "iconName": "tea",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "coffee",
      "iconName": "coffee",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "hot chocolate",
      "iconName": "hot-chocolate",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "fruit",
      "iconName": "fruit",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "apple",
      "iconName": "apple",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "banana",
      "iconName": "banana",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "orange",
      "iconName": "orange-fruit",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "pear",
      "iconName": "pear",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "lemon",
      "iconName": "lemon",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "grape",
      "iconName": "grape",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "raisin",
      "iconName": "raisin",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "blackcurrant",
      "iconName": "blackcurrant",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "strawberry",
      "iconName": "strawberry",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "raspberry",
      "iconName": "raspberry",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "blueberry",
      "iconName": "blueberry",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "cherry",
      "iconName": "cherry",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }]
  },

  "people": {
    "name": "board6",
    "rows": 6,
    "columns": 9,
    "tiles": [{
      "type": "link",
      "displayName": "Back",
      "iconName": "navigate-back",
      "linkTo": "main",
      "colour": "linkColour"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "adult",
      "iconName": "adult",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "child",
      "iconName": "child",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "mum",
      "iconName": "mum",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "dad",
      "iconName": "dad",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "man",
      "iconName": "man",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "boy",
      "iconName": "boy",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "sister",
      "iconName": "sister",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "brother",
      "iconName": "brother",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "woman",
      "iconName": "woman",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "girl",
      "iconName": "girl",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "grandma",
      "iconName": "grandma",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "grandad",
      "iconName": "grandad",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "baby",
      "iconName": "baby",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "nana",
      "iconName": "nana",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "nice",
      "iconName": "nice",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "mean",
      "iconName": "mean",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textOnly",
      "displayName": "his",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "him",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "her",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "they",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "them",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textOnly",
      "displayName": "their",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "old",
      "iconName": "old",
      "colour": "blue",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "young",
      "iconName": "young",
      "colour": "blue",
      "linkTo": "main"
    }]
  },

  "feelings": {
    "name": "board6",
    "rows": 6,
    "columns": 9,
    "tiles": [{
      "type": "link",
      "displayName": "Back",
      "iconName": "navigate-back",
      "linkTo": "main",
      "colour": "linkColour"
    }, {
      "type": "textAndIcon",
      "displayName": "happy",
      "iconName": "happy",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sad",
      "iconName": "sad",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "OK",
      "iconName": "ok",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "smile",
      "iconName": "smile",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "sick",
      "iconName": "sick",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "win",
      "iconName": "win",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "easy",
      "iconName": "easy",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "angry",
      "iconName": "angry",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "laugh",
      "iconName": "laugh",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "lose",
      "iconName": "lose",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "hard",
      "iconName": "hard",
      "colour": "green",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "worried",
      "iconName": "worried",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "frustrated",
      "iconName": "frustrated",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "excited",
      "iconName": "excited",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "textAndIcon",
      "displayName": "embarrassed",
      "iconName": "embarrassed",
      "colour": "orange",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "birthday",
      "iconName": "birthday",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "christmas",
      "iconName": "christmas",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "easter",
      "iconName": "easter",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "eid",
      "iconName": "eid",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "textAndIcon",
      "displayName": "ramadam",
      "iconName": "ramadam",
      "colour": "grey",
      "linkTo": "main"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }, {
      "type": "blank"
    }]
  }
}

for(const board in boards){

  boards[board].tiles.forEach( tile => {

    if(tile.type == "blank") return

    tile.internalName = tile.displayName

  })

}

console.log(JSON.stringify(boards))
