const boards = [{ // LITTLE
  name: "board0",
  rows: 3,
  columns: 6,
  tiles: [
    ["want", "green"],
    ["more", "blue"],
    ["not", "grey"],
    ["go", "green"],
    ["help", "green"],
    ["look", "green"],
    ["play", "green"],
    ["same", "blue"],
    ["different", "blue"],
    ["what", "pink"],
    ["like", "green"],
    ["stop", "green"],
    ["drink", "green"],
    ["eat", "green"],
    ["turn", "grey"],
    ["up", "red"],
    ["down", "red"],
    ["finish", "green"],
  ]
},
{ // MAIN
  name: "board1",
  rows: 6,
  columns: 9,
  master: true,
  tiles: [
    ["LToys", "white"],
    ["LLearn", "white"],
    ["LTopic", "white"],
    ["LBody", "white"],
    ["LHome", "white"],
    ["LFood", "white"],
    ["LDrinks", "white"],
    ["LPeople", "white"],
    ["LFeelings", "white"],
    ["I", "yellow"],
    ["want", "green"],
    ["more", "blue"],
    ["not", "grey"],
    ["go", "green"],
    ["help", "green"],
    ["look", "green"],
    ["need", "green"],
    ["have", "green"],
    ["you", "yellow"],
    ["play", "green"],
    ["same", "blue"],
    ["different", "blue"],
    ["what", "pink"],
    ["like", "green"],
    ["stop", "green"],
    ["where", "pink"],
    ["in", "red"],
    ["he", "yellow"],
    ["eat", "green"],
    ["drink", "green"],
    ["turn", "green"],
    ["up", "red"],
    ["down", "red"],
    ["finish", "green"],
    ["who", "pink"],
    ["on", "red"],
    ["she", "yellow"],
    ["do", "green"],
    ["loud", "blue"],
    ["quiet", "blue"],
    ["fast", "blue"],
    ["slow", "blue"],
    ["funny", "blue"],
    ["talk", "green"],
    ["off", "red"],
    ["it", "yellow"],
    ["put", "green"],
    ["make", "green"],
    ["feel", "green"],
    ["think", "green"],
    ["is", "green"],
    ["close", "green"],
    ["open", "green"],
    ["here", "grey"],
  ]
},
{ // TOYS
  name: "board2",
  rows: 6,
  columns: 9,
  sub: true,
  source: 1,
  tiles: [
    ["-", "-"],
    ["toy", "grey"],
    ["game", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["computer", "grey"],
    ["tablet", "grey"],
    ["phone", "grey"], //one missing here for back button
    ["ball", "grey"],
    ["bubbles", "grey"],
    ["balloon", "grey"],
    ["blocks", "grey"],
    ["foam", "grey"],
    ["spinner", "grey"],
    ["yo-yo", "grey"],
    ["stretch bands", "grey"],
    ["wind up", "grey"],
    ["jigsaw", "grey"],
    ["mr potato", "grey"],
    ["dice", "grey"],
    ["doll", "grey"],
    ["teddy", "grey"],
    ["board game", "grey"],
    ["book", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["sing", "green"],
    ["music", "grey"],
    ["dance", "green"],
    ["clap", "green"],
    ["tickle", "green"],
    ["push", "green"],
    ["climb", "green"],
    ["read", "green"],
    ["-", "-"],
    ["sand pit", "grey"],
    ["water tray", "grey"],
    ["swing", "grey"],
    ["slide", "grey"],
    ["roundabout", "grey"],
    ["seesaw", "grey"],
    ["ladder", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["bike", "grey"],
    ["scooter", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
  ]
},
{ // LEARN
  name: "board3",
  rows: 6,
  columns: 9,
  sub: true,
  source: 1,
  tiles: [
    /*[back]*/
    ["-", "-"],
    ["⠀0⠀", "grey"],
    ["add", "grey"],
    ["minus", "grey"],
    ["divide", "grey"],
    ["times", "grey"],
    ["equals", "grey"],
    ["-", "-"],
    ["count", "grey"],
    ["⠀1⠀", "grey"],
    ["⠀2⠀", "grey"],
    ["⠀3⠀", "grey"],
    ["⠀4⠀", "grey"],
    ["⠀5⠀", "grey"],
    ["⠀6⠀", "grey"],
    ["⠀7⠀", "grey"],
    ["⠀8⠀", "grey"],
    ["⠀9⠀", "grey"],
    ["learn", "green"],
    ["cut", "green"],
    ["colour", "green"],
    ["paint", "green"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["red", "red"],
    ["orange", "red"],
    ["yellow", "red"],
    ["green", "red"],
    ["blue", "red"],
    ["purple", "red"],
    ["pink", "red"],
    ["black", "red"],
    ["brown", "red"],
    ["stripes", "red"],
    ["dots", "red"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["grey", "red"],
    ["pen", "grey"],
    ["pencil", "grey"],
    ["scissors", "grey"],
    ["sharpener", "grey"],
    ["ruler", "grey"],
    ["glitter", "grey"],
    ["light", "grey"],
    ["-", "-"],
    ["dark", "grey"],
  ]
},
{ // TOPIC
  name: "board4",
  rows: 6,
  columns: 9,
  sub: true,
  source: 1,
  tiles: [
    /*[back]*/
    ["-", "-"],
    ["animal", "grey"],
    ["pet", "grey"],
    ["zoo", "grey"],
    ["farm", "grey"],
    ["wild", "grey"],
    ["fluffy", "pink"],
    ["-", "-"],
    ["big", "pink"],
    ["cat", "grey"],
    ["dog", "grey"],
    ["rabbit", "grey"],
    ["hamster", "grey"],
    ["lizard", "grey"],
    ["tortoise", "grey"],
    ["snake", "grey"],
    ["bird", "grey"],
    ["-", "-"],
    ["cow", "grey"],
    ["sheep", "grey"],
    ["chicken", "grey"],
    ["horse", "grey"],
    ["pig", "grey"],
    ["elephant", "grey"],
    ["spider", "grey"],
    ["bug", "grey"],
    ["small", "pink"],
    ["car", "grey"],
    ["bus", "grey"],
    ["train", "grey"],
    ["motorbike", "grey"],
    ["plane", "grey"],
    ["helicopter", "grey"],
    ["boat", "grey"],
    ["paw", "grey"],
    ["tail", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["claw", "grey"],
    ["-", "-"],
    ["wheel", "grey"],
    ["-", "-"],
    ["left", "pink"],
    ["-", "-"],
    ["right", "pink"],
    ["-", "-"],
    ["drive", "green"],
    ["fly", "green"],
    ["ride", "green"],
  ]
},
{ // BODY
  name: "board5",
  rows: 6,
  columns: 9,
  sub: true,
  source: 1,
  tiles: [
    /*[back]*/
    ["-", "-"],
    ["body", "grey"],
    ["poo", "grey"],
    ["wee", "grey"],
    ["hurt", "grey"],
    ["blood", "grey"],
    ["itch", "grey"],
    ["broken", "grey"],
    ["bruise", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["nappy", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["finger", "grey"],
    ["hand", "grey"],
    ["arm", "grey"],
    ["elbow", "grey"],
    ["tummy", "grey"],
    ["private parts", "grey"],
    ["eye", "grey"],
    ["nose", "grey"],
    ["mouth", "grey"],
    ["toe", "grey"],
    ["foot", "grey"],
    ["leg", "grey"],
    ["knee", "grey"],
    ["chest", "grey"],
    ["head", "grey"],
    ["ear", "grey"],
    ["hair", "grey"],
    ["tooth", "grey"],
    ["pants", "grey"],
    ["socks", "grey"],
    ["shoe", "grey"],
    ["trousers", "grey"],
    ["shorts", "grey"],
    ["shirt", "grey"],
    ["skirt", "grey"],
    ["tights", "grey"],
    ["jumper", "grey"],
    ["-", "-"],
    ["zip", "grey"],
    ["button", "grey"],
    ["lace", "grey"],
    ["velcro", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["coat", "grey"],
    ["-", "-"],
  ]
},
{ // HOME
  name: "board5",
  rows: 6,
  columns: 9,
  sub: true,
  source: 1,
  tiles: [
    /*[back]*/
    ["-", "-"],
    ["school", "blue"],
    ["home", "blue"],
    ["park", "blue"],
    ["swimming pool", "blue"],
    ["restaurant", "blue"],
    ["shop", "blue"],
    ["outside", "grey"],
    ["weather", "pink"],
    ["toilet", "blue"],
    ["kitchen", "blue"],
    ["living room", "blue"],
    ["bedroom", "blue"],
    ["bathroom", "blue"],
    ["dining room", "blue"],
    ["stairs", "blue"],
    ["garden", "blue"],
    ["rain", "grey"],
    ["cooker", "grey"],
    ["soap", "grey"],
    ["chair", "grey"],
    ["bed", "grey"],
    ["swim", "green"],
    ["table", "grey"],
    ["buy", "green"],
    ["window", "grey"],
    ["sun", "grey"],
    ["cook", "green"],
    ["sponge", "grey"],
    ["sofa", "grey"],
    ["sleep", "green"],
    ["bath", "grey"],
    ["cutlery", "grey"],
    ["money", "grey"],
    ["door", "grey"],
    ["cloud", "grey"],
    ["-", "-"],
    ["towel", "grey"],
    ["TV", "grey"],
    ["-", "-"],
    ["sink", "grey"],
    ["dish", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["mud", "grey"],
    ["-", "-"],
    ["wash", "green"],
    ["sit", "green"],
    ["-", "-"],
    ["shower", "grey"],
    ["-", "-"],
    ["hot", "pink"],
    ["cold", "pink"],
    ["snow", "grey"],
  ]
},
{ // Food
  name: "board6",
  rows: 6,
  columns: 9,
  sub: true,
  source: 1,
  tiles: [
    /*[back]*/
    ["-", "-"],
    ["food", "grey"],
    ["-", "-"],
    ["sauce", "grey"],
    ["-", "-"],
    ["breakfast", "grey"],
    ["lunch", "grey"],
    ["tea", "grey"],
    ["snack", "grey"],
    ["meal", "grey"],
    ["mash", "grey"],
    ["curry", "grey"],
    ["rice", "grey"],
    ["pasta", "grey"],
    ["pizza", "grey"],
    ["favourite", "pink"],
    ["burned", "pink"],
    ["healthy", "pink"],
    ["veg", "grey"],
    ["carrot", "grey"],
    ["broccoli", "grey"],
    ["potato", "grey"],
    ["pea", "grey"],
    ["bean", "grey"],
    ["tomato", "grey"],
    ["salad", "grey"],
    ["bread", "grey"],
    ["meat", "grey"],
    ["fish", "grey"],
    ["ham", "grey"],
    ["chicken", "grey"],
    ["tuna", "grey"],
    ["nugget", "grey"],
    ["burger", "grey"],
    ["sausage", "grey"],
    ["toast", "grey"],
    ["cereal", "grey"],
    ["egg", "grey"],
    ["-", "-"],
    ["cheese", "grey"],
    ["chocolate", "grey"],
    ["biscuit", "grey"],
    ["crisp", "grey"],
    ["chip", "grey"],
    ["sandwich", "grey"],
    ["soup", "grey"],
    ["noodles", "grey"],
    ["pancake", "grey"],
    ["yogurt", "grey"],
    ["butter", "grey"],
    ["jam", "grey"],
    ["sweet", "pink"],
    ["spicy", "pink"],
    ["wrap", "grey"],
  ]
},
{ // Drinks
  name: "board7",
  rows: 6,
  columns: 9,
  sub: true,
  source: 1,
  tiles: [
    /*[back]*/
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["hot", "blue"],
    ["-", "-"],
    ["cold", "blue"],
    ["-", "-"],
    ["-", "-"],

    ["juice", "orange"],
    ["water", "orange"],
    ["milk", "orange"],
    ["milkshake", "orange"],
    ["fizzy", "orange"],
    ["lemonade", "orange"],
    ["cola", "orange"],
    ["-", "-"],
    ["-", "-"],

    ["tea", "orange"],
    ["coffee", "orange"],
    ["hot chocolate", "orange"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],

    ["fruit", "grey"],
    ["apple", "grey"],
    ["banana", "grey"],
    ["orange", "grey"],
    ["pear", "grey"],
    ["lemon", "grey"],
    ["grape", "grey"],
    ["raisin", "grey"],
    ["blackcurrant", "grey"],

    ["strawberry", "grey"],
    ["raspberry", "grey"],
    ["blueberry", "grey"],
    ["cherry", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],

    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
  ]
},
{ // People
  name: "board6",
  rows: 6,
  columns: 9,
  sub: true,
  source: 1,
  tiles: [
    /*[back]*/
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["adult", "orange"],
    ["child", "orange"],
    ["-", "-"],
    ["mum", "orange"],
    ["dad", "orange"],
    ["-", "-"],
    ["man", "orange"],
    ["boy", "orange"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["sister", "orange"],
    ["brother", "orange"],
    ["-", "-"],
    ["woman", "orange"],
    ["girl", "orange"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["grandma", "orange"],
    ["grandad", "orange"],
    ["-", "-"],
    ["baby", "orange"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["nana", "orange"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["nice", "orange"],
    ["-", "-"],
    ["mean", "orange"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["his", "green"],
    ["him", "green"],
    ["her", "green"],
    ["they", "green"],
    ["them", "green"],
    ["their", "green"],
    ["old", "blue"],
    ["-", "-"],
    ["young", "blue"],
  ]
},
{ // Feelings
  name: "board6",
  rows: 6,
  columns: 9,
  sub: true,
  source: 1,
  tiles: [
    /*[back]*/
    ["-", "-"],
    ["happy", "orange"],
    ["sad", "orange"],
    ["OK", "orange"],
    ["smile", "green"],
    ["sick", "orange"],
    ["win", "green"],
    ["easy", "green"],
    ["angry", "orange"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["laugh", "green"],
    ["-", "-"],
    ["lose", "green"],
    ["hard", "green"],
    ["worried", "orange"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["frustrated", "orange"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["excited", "orange"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["embarrassed", "orange"],
    ["birthday", "grey"],
    ["christmas", "grey"],
    ["easter", "grey"],
    ["eid", "grey"],
    ["ramadam", "grey"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
    ["-", "-"],
  ]
},
]

boards.forEach(board => {

  oldTiles = board.tiles
  board.tiles = []

  oldTiles.forEach( oldTile => {

    if(oldTile[0] === "-"){
      board.tiles.push ( { type:"blank", } )
      return
    }

    let newTile = {
      type:"textAndIcon",
      displayName: oldTile[0],
      iconName: oldTile[0].toLowerCase().replaceAll(" ","-"),
      colour: oldTile[1],
    }

    if( board.sub ) newTile.returnTo = "main"

    board.tiles.push( newTile )

  })

})

console.log(JSON.stringify(boards))